# docker-compose.yml
version: "3.9"
# Mention: issues with port 5000 that I could not tackle so changed to port 5001
services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      API_KEY: supertopsecretkey!